spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/vocabulary_quiz?currentSchema=public
    username: root
    password: root@123456
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 5
  flyway:
    table: flyway_schema_history_core
    baseline-on-migrate: true
    baseline-version: 0.0.0
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

logging:
  level:
    root: info
